window.DB_SNAPSHOT = {
  "products": [
    {
      "id": 1,
      "classification_id": 1,
      "brand_id": 1,
      "category_id": 1,
      "sku": "SMC-CP-01",
      "slug": "cuplock-scaffolding",
      "name_en": "Cuplock Scaffolding System",
      "name_ar": "نظام سقالات الكابلوك المعياري",
      "tagline_en": "The Kingdom’s Proven Modular Access & Shoring Backbone",
      "tagline_ar": "العمود الفقري المعتمد للسقالات المعمارية والتدعيم بالمملكة",
      "short_summary_en": "A modular steel scaffolding system using cup-type locking connections between standards and ledgers, fabricated in Riyadh according to SASO standards.",
      "short_summary_ar": "نظام سقالات فولاذي تركيبي يعتمد على آلية أقفال الأكواب الدائرية المتينة لربط القوائم والأذرع الأفقية، مصنع بالرياض وفق معايير الهيئة السعودية للمواصفات.",
      "what_is_it_en": "A heavy-duty, fast-erecting multi-point node scaffolding system manufactured from high-yield structural steel tubes.",
      "what_is_it_ar": "نظام سقالات عالي التحمل يعتمد على عقد التثبيت بالأكواب السريعة، مصنع من أنابيب الفولاذ الإنشائي عالي المقاومة.",
      "what_is_used_for_en": "Temporary access, safe working platforms, facade maintenance, and medium-to-heavy structural falsework support during concrete casting.",
      "what_is_used_for_ar": "توفير منصات عمل آمنة، صيانة الواجهات، والتدعيم الإنشائي الموثوق خلال مراحل صب الخرسانة المسلحة.",
      "how_does_it_work_en": "Standards incorporate fixed bottom cups welded at 500mm intervals. Loose top cups slide down and rotate over ledger blade ends, locking up to four horizontal components with a single hammer blow.",
      "how_does_it_work_ar": "تتضمن القوائم أكواباً سفلية ملحومة كل 500 مم، وينزلق كوب علوي متحرك فوق نهايات العوارض ليقفل حتى 4 اتجاهات بضربة مطرقة واحدة.",
      "key_advantages_en": [
        "Rapid hammer-strike node locking without loose bolts",
        "High yield S355 steel with hot-dip galvanizing",
        "Zero maintenance wear nodes tested to SASO 2874",
        "High local inventory available for 24-hr site delivery"
      ],
      "key_advantages_ar": [
        "إغلاق سريع بضربة مطرقة دون مسامير مفقودة",
        "فولاذ عالي المقاومة مجلفن بالغمس الساخن",
        "عقد مقاومة للاهتراء معتمدة ومختبرة وفق ساسو",
        "مخزون ضخم جاهز للتوريد الفوري خلال 24 ساعة"
      ],
      "main_components_en": [
        "Standard (Vertical)",
        "Ledger (Horizontal)",
        "Transom",
        "Base Jack",
        "Swivel Face Brace",
        "Steel Walkway Planks"
      ],
      "main_components_ar": [
        "قائم رأسي",
        "ذراع أفقي",
        "عارضة أرضية",
        "قاعدة لولبية قابلة للضبط",
        "مقص تثبيت قطري",
        "ألواح مشاية فولاذية"
      ],
      "technical_specs": {
        "tube_diameter": "48.3 mm",
        "wall_thickness": "3.2 mm / 3.6 mm",
        "steel_grade": "S275J2H / S355JR",
        "node_capacity": "58 kN vertical load",
        "coating": "Hot-Dip Galvanized ≥ 65 µm",
        "saso_norm": "SASO 2874 / BS 1139"
      },
      "sales_available": 1,
      "rental_available": 1,
      "regional_availability": [
        "KSA",
        "GCC",
        "MENA",
        "AFRICA"
      ],
      "hero_image": "images/products/cuplock-scaffolding.jpg",
      "main_image": "images/products/cuplock-scaffolding.jpg",
      "drawing_url": "/assets/drawings/cuplock-technical.pdf",
      "brochure_url": "/assets/brochures/sm-cuplock.pdf",
      "video_url": null,
      "status": "PUBLISHED",
      "featured": 1,
      "display_order": 1,
      "meta_title_en": null,
      "meta_title_ar": null,
      "meta_desc_en": null,
      "meta_desc_ar": null,
      "created_by": null,
      "updated_by": null,
      "created_at": "2026-09-28 21:12:59",
      "updated_at": "2026-09-28 21:12:59",
      "class_code": "LOCAL",
      "brand_name": "Saudi Master",
      "cat_slug": "scaffolding"
    },
    {
      "id": 2,
      "classification_id": 1,
      "brand_id": 1,
      "category_id": 5,
      "sku": "SMC-MH-02",
      "slug": "manhole-systems",
      "name_en": "Manhole Formwork Systems",
      "name_ar": "نظام قوالب المناهل وغرف التفتيش",
      "tagline_en": "Engineered Reusable Steel Moulds for Underground Infrastructure",
      "tagline_ar": "قوالب فولاذية متطورة قابلة لإعادة الاستخدام لغرف الخدمات والسيول",
      "short_summary_en": "A reusable forming and construction solution manufactured in KSA for pouring square, rectangular, and round concrete manhole structures.",
      "short_summary_ar": "حل متكامل مصنع محلياً لصب غرف التفتيش وخطوط الخدمات الخرسانية بالأشكال المربعة والدائرية بأعلى دقة.",
      "what_is_it_en": "Rigid external steel shuttering panels paired with a proprietary collapsible internal core mechanism for high-frequency municipal utility casting.",
      "what_is_it_ar": "ألواح فولاذية خارجية عالية الصلابة مع قلب داخلي قابل للانكماش السريع لصب غرف الخدمات البلدية المتكررة.",
      "what_is_used_for_en": "Underground municipal stormwater drainage, electrical cable vaults, sanitary sewer chambers, and telecom duct banks.",
      "what_is_used_for_ar": "شبكات تصريف مياه الأمطار والسيول، غرف سحب الكابلات الكهربائية، شبكات الصرف الصحي، ومسارات الاتصالات.",
      "how_does_it_work_en": "Inner core contracts inward via corner toggle hinges or central turnbuckles once concrete reaches initial set, allowing the assembly to be stripped and craned in minutes.",
      "how_does_it_work_ar": "ينكمش القلب الداخلي نحو المركز بواسطة مفصلات ركنية ومشدات ميكانيكية فور تصلب الخرسانة الأولي، مما يتيح فك القالب ورفعه بالرافعة خلال دقائق.",
      "key_advantages_en": [
        "Zero plywood waste across 200+ pours",
        "Collapsible corner keys for 15-minute striking",
        "Hydrostatic concrete pressure capacity up to 60 kN/m²",
        "Bespoke dimensions matching MOMRA & NWC specs"
      ],
      "key_advantages_ar": [
        "انعدام هدر الخشب عبر أكثر من 200 صبة متتالية",
        "زوايا مفصلية تنكمش للفك خلال 15 دقيقة فقط",
        "تحمل ضغط خرسانة هيدروستاتيكي حتى 60 كيلو نيوتن/م²",
        "أبعاد تفصيلية معتمدة من وزارة الشؤون البلدية وشركة المياه الوطنية"
      ],
      "main_components_en": [
        "Collapsible Core Panels",
        "Rigid Outer Corner Units",
        "Walers & Alignment Braces",
        "Tie-Rod Assemblies",
        "Lifting Eyes"
      ],
      "main_components_ar": [
        "ألواح القلب الداخلي المنكمش",
        "وحدات الزوايا الخارجية",
        "كمرات تدعيم وأذرع موازنة",
        "مسامير الشد والربط",
        "نقاط الرفع المعيارية"
      ],
      "technical_specs": {
        "steel_face_thickness": "5.0 mm plate",
        "frame_profile": "100x50 mm boxed channel",
        "max_pour_height": "4.5 m single lift",
        "permissible_pressure": "60 kN/m²",
        "striking_mechanism": "Mechanical ratchet toggle"
      },
      "sales_available": 1,
      "rental_available": 1,
      "regional_availability": [
        "KSA",
        "GCC",
        "MENA"
      ],
      "hero_image": "images/products/manhole-systems.jpg",
      "main_image": "images/products/manhole-systems.jpg",
      "drawing_url": "/assets/drawings/manhole-formwork.pdf",
      "brochure_url": "/assets/brochures/sm-manhole.pdf",
      "video_url": null,
      "status": "PUBLISHED",
      "featured": 1,
      "display_order": 2,
      "meta_title_en": null,
      "meta_title_ar": null,
      "meta_desc_en": null,
      "meta_desc_ar": null,
      "created_by": null,
      "updated_by": null,
      "created_at": "2026-09-28 21:12:59",
      "updated_at": "2026-09-28 21:12:59",
      "class_code": "LOCAL",
      "brand_name": "Saudi Master",
      "cat_slug": "precast-custom"
    },
    {
      "id": 3,
      "classification_id": 1,
      "brand_id": 1,
      "category_id": 2,
      "sku": "SMC-CC-03",
      "slug": "circular-column-systems",
      "name_en": "Circular Column Systems",
      "name_ar": "نظام قوالب الأعمدة الدائرية",
      "tagline_en": "Precision Rolled Steel Halves for Flawless Fair-Faced Geometry",
      "tagline_ar": "أنصاف قوالب فولاذية مدرفلة للأعمدة الخرسانية الدائرية الصقيلة",
      "short_summary_en": "Precision rolled two-half steel shuttering systems manufactured in Saudi Arabia for casting smooth, fair-faced circular columns.",
      "short_summary_ar": "نظام شدات فولاذية نصف دائرية مصنعة محلياً بأعلى دقة لصب الأعمدة الأسطوانية بأسطح معمارية ناعمة.",
      "what_is_it_en": "Heavy cylindrical steel shells with integrated perimeter connection flanges and alignment wedges, handling rapid vertical concrete placement.",
      "what_is_it_ar": "قوالب أسطوانية مسبوكة من صفائح فولاذية ثقيلة ذات حواف ربط محيطية ومفاتيح إسفينية تضمن إحكام الإغلاق.",
      "what_is_used_for_en": "Commercial tower entrance columns, metro viaduct piers, high-ceiling architectural atriums, and infrastructure bridge supports.",
      "what_is_used_for_ar": "أعمدة مداخل الأبراج التجارية، ركائز جسور المترو، الردهات المعمارية الشاهقة، وأعمدة الجسور العلوية.",
      "how_does_it_work_en": "Two pre-curved steel half-shells bolt or wedge together securely. Concrete is placed in a single continuous lift, producing uniform fair-faced results without tie holes across the face.",
      "how_does_it_work_ar": "يتم جمع نصفي القالب بروابط إسفينية أو براغي محيطية سريعة. تصب الخرسانة دفعة واحدة وتنتج سطحاً صقيلاً خالياً من ثقوب مسامير الزرجينة.",
      "key_advantages_en": [
        "Architectural Class A mirror-smooth concrete surface",
        "No internal through-ties required across column diameter",
        "Integrated pouring funnel and working platform brackets",
        "Available in stock from Ø300mm to Ø2000mm"
      ],
      "key_advantages_ar": [
        "أسطح خرسانية فائقة النعومة Class A دون تشطيب إضافي",
        "لا تتطلب زراجين داخلية عبر جسم العمود إطلاقاً",
        "منصات صب مدمجة وقمع توجيه الخرسانة بأعلى معايير السلامة",
        "متوفرة بمخازننا من قطر 300 مم حتى 2000 مم"
      ],
      "main_components_en": [
        "Rolled Semi-Cylindrical Shells",
        "Quick-Connect Wedge Clamps",
        "Push-Pull Plumbing Struts",
        "Integrated Access Ladder & Platform"
      ],
      "main_components_ar": [
        "أنصاف أسطوانية مدرفلة",
        "قمطات إسفينية سريعة الإغلاق",
        "دعامات ضبط الرأسية ثنائية الاتجاه",
        "سلم ومنصة عمل معتمدة"
      ],
      "technical_specs": {
        "diameter_range": "300 mm – 2000 mm",
        "standard_heights": "0.5m, 1.0m, 1.5m, 2.0m, 3.0m",
        "max_pour_pressure": "100 kN/m² hydrostatic",
        "shell_thickness": "4.0 mm – 6.0 mm S355 steel"
      },
      "sales_available": 1,
      "rental_available": 1,
      "regional_availability": [
        "KSA",
        "GCC",
        "MENA"
      ],
      "hero_image": "images/products/circular-column-systems.jpg",
      "main_image": "images/products/circular-column-systems.jpg",
      "drawing_url": "/assets/drawings/circular-column.pdf",
      "brochure_url": "/assets/brochures/sm-circular.pdf",
      "video_url": null,
      "status": "PUBLISHED",
      "featured": 1,
      "display_order": 3,
      "meta_title_en": null,
      "meta_title_ar": null,
      "meta_desc_en": null,
      "meta_desc_ar": null,
      "created_by": null,
      "updated_by": null,
      "created_at": "2026-09-28 21:12:59",
      "updated_at": "2026-09-28 21:12:59",
      "class_code": "LOCAL",
      "brand_name": "Saudi Master",
      "cat_slug": "formwork"
    },
    {
      "id": 4,
      "classification_id": 1,
      "brand_id": 1,
      "category_id": 5,
      "sku": "SMC-PC-04",
      "slug": "precast-panels",
      "name_en": "Precast Concrete Panel Moulds",
      "name_ar": "قوالب الألواح الخرسانية مسبقة الصب",
      "tagline_en": "Industrial Tilting Tables and Battery Moulds Built for Off-Site Speed",
      "tagline_ar": "طاولات قلابة وقوالب بطاريات صناعية للتصنيع الخرساني المسبق",
      "short_summary_en": "Factory-produced heavy industrial moulds and tilting beds engineered in KSA for repetitive precast concrete wall elements and boundary enclosures.",
      "short_summary_ar": "قوالب وطاولات هيدروليكية قلابة مصنعة بالكامل بالمملكة لإنتاج عناصر الحوائط والأسوار الخرسانية مسبقة الصب.",
      "what_is_it_en": "Machined steel casting beds with integrated magnetic side formers, heating pipe conduits, and hydraulic tilt mechanisms.",
      "what_is_it_ar": "أسرة صب فولاذية دقيقة التشغيل مجهزة بحواجز مغناطيسية وتمديدات تسخين ومكابس هيدروليكية لرفع الألواح دون إجهاد.",
      "what_is_used_for_en": "National border security walls, modular housing panels, warehouse tilt-up panels, and civil retaining walls.",
      "what_is_used_for_ar": "الأسوار الأمنية الحدودية، الوحدات السكنية المعيارية، حوائط المستودعات، وحوائط الاستناد مسبقة الصنع.",
      "how_does_it_work_en": "Rebar cages are placed onto the polished steel deck. Concrete is poured, vibrated via integral high-frequency vibrators, cured, and tilted up to 80° for safe crane demoulding.",
      "how_does_it_work_ar": "يوضع حديد التسليح على السطح الفولاذي المصقول وتصب الخرسانة مع هزازات ترددية مدمجة، ثم تمال الطاولة هيدروليكياً حتى 80 درجة لتفريغ اللوح بسلاسة.",
      "key_advantages_en": [
        "Sub-millimeter flatness tolerances across 14-meter table lengths",
        "Hydraulic tilting up to 80° preventing green-concrete cracking",
        "Adaptable magnetic edge shutters for infinite panel widths",
        "Fabricated with domestic high-grade steel"
      ],
      "key_advantages_ar": [
        "استواء سطحي دقيق بأقل من ملليمتر على امتداد 14 متراً",
        "إمالة هيدروليكية سلسة حتى 80 درجة تمنع تشقق الخرسانة الطرية",
        "حواجز جانبية مغناطيسية تتيح تعديل سماكة وعرض اللوح بحرية",
        "تصنيع وطني بأجود أنواع الفولاذ الإنشائي"
      ],
      "main_components_en": [
        "Polished Steel Decking Table",
        "Hydraulic Lift Cylinders",
        "Magnetic Side Rails",
        "Compaction Vibration System",
        "Thermal Curing Tubes"
      ],
      "main_components_ar": [
        "طاولة الصب الفولاذية المصقولة",
        "اسطوانات الرفع الهيدروليكية",
        "حواجز التثبيت المغناطيسية",
        "منظومة الهز الترددي",
        "مواسير الإنضاج الحراري"
      ],
      "technical_specs": {
        "standard_table_width": "3.5 m – 4.5 m",
        "standard_length": "12 m – 100 m",
        "max_capacity": "1,000 kg/m²",
        "tilting_angle": "0° to 83° hydraulic",
        "deck_plate": "8.0 mm machined plate"
      },
      "sales_available": 1,
      "rental_available": 1,
      "regional_availability": [
        "KSA",
        "GCC"
      ],
      "hero_image": "images/products/precast-panels.jpg",
      "main_image": "images/products/precast-panels.jpg",
      "drawing_url": "/assets/drawings/precast-table.pdf",
      "brochure_url": "/assets/brochures/sm-precast.pdf",
      "video_url": null,
      "status": "PUBLISHED",
      "featured": 0,
      "display_order": 4,
      "meta_title_en": null,
      "meta_title_ar": null,
      "meta_desc_en": null,
      "meta_desc_ar": null,
      "created_by": null,
      "updated_by": null,
      "created_at": "2026-09-28 21:12:59",
      "updated_at": "2026-09-28 21:12:59",
      "class_code": "LOCAL",
      "brand_name": "Saudi Master",
      "cat_slug": "precast-custom"
    },
    {
      "id": 5,
      "classification_id": 1,
      "brand_id": 1,
      "category_id": 2,
      "sku": "SMC-GS-05",
      "slug": "grinder-steel-shutter",
      "name_en": "Grinder Steel Shutter",
      "name_ar": "شدات جريندر الفولاذية الثقيلة",
      "tagline_en": "Heavy-Duty Structural Steel Shuttering for Massive Repetitive Casting",
      "tagline_ar": "شدات معدنية فائقة الصلابة مصممة لمئات التكرارات في المنشآت الضخمة",
      "short_summary_en": "An extra-heavy duty fabricated steel shutter and formwork system engineered for non-deflecting repetitive casting in major Saudi civil works.",
      "short_summary_ar": "نظام شدات فولاذية متينة مصنعة للأعمال الشاقة تتحمل دورات صب متكررة لمئات المرات دون أي انحناء.",
      "what_is_it_en": "High-moment steel walers welded directly to 5mm faceplates with robust external taper-tie connection points.",
      "what_is_it_ar": "كمرات فولاذية جسيمة ملحومة مباشرة بصفائح 5 مم مع نقاط شد خارجية تضمن مقاومة الضغوط القصوى.",
      "what_is_used_for_en": "Massive retaining walls, deep basement perimeters, strategic water storage reservoirs, and power plant substations.",
      "what_is_used_for_ar": "الجدران الاستنادية الضخمة، جدران الأقبية العميقة، خزانات المياه الاستراتيجية، ومحطات تحويل الطاقة.",
      "how_does_it_work_en": "Large modular crane-handled gangs are coupled together with high-shear pins. Concrete is placed in high-velocity lifts without risk of face bulge.",
      "how_does_it_work_ar": "تجمع الألواح في مجموعات كبيرة ترفع بالرافعة وتثبت بمسامير قص متينة لتتحمل سرعات صب خرساني عالية بأمان تام.",
      "key_advantages_en": [
        "Over 300 successful pour reuses with minimal maintenance",
        "Eliminates surface plywood replacement costs",
        "Engineered for 90 kN/m² hydrostatic concrete pressure",
        "Complete local parts availability in Riyadh and Dammam"
      ],
      "key_advantages_ar": [
        "أكثر من 300 صبة متكررة مع صيانة دورية ميسرة",
        "إلغاء تكاليف تغيير الخشب الرقائقي التالف نهائياً",
        "مصممة لتحمل ضغط خرسانة هائل حتى 90 كيلو نيوتن/م²",
        "قطع الغيار متوفرة فوراً في مستودعات الرياض والدمام"
      ],
      "main_components_en": [
        "All-Steel Shutter Panels",
        "Integrated Stiffener Walers",
        "Heavy-Duty Tie Wedges",
        "Crane Lifting Hooks"
      ],
      "main_components_ar": [
        "ألواح الشدات الفولاذية بالكامل",
        "كمرات التقوية المدمجة",
        "أوتاد الشد والتثبيت القوي",
        "خطافات الرفع الآمن بالرافعة"
      ],
      "technical_specs": {
        "faceplate_steel": "5.0 mm S355 Structural Steel",
        "frame_depth": "150 mm welded profile",
        "max_permissible_pressure": "90 kN/m²",
        "crane_handling": "Integrated 2.5t lift lugs"
      },
      "sales_available": 1,
      "rental_available": 1,
      "regional_availability": [
        "KSA",
        "GCC",
        "MENA"
      ],
      "hero_image": "images/products/grinder-steel-shutter.jpg",
      "main_image": "images/products/grinder-steel-shutter.jpg",
      "drawing_url": "/assets/drawings/grinder-shutter.pdf",
      "brochure_url": "/assets/brochures/sm-grinder.pdf",
      "video_url": null,
      "status": "PUBLISHED",
      "featured": 0,
      "display_order": 5,
      "meta_title_en": null,
      "meta_title_ar": null,
      "meta_desc_en": null,
      "meta_desc_ar": null,
      "created_by": null,
      "updated_by": null,
      "created_at": "2026-09-28 21:12:59",
      "updated_at": "2026-09-28 21:12:59",
      "class_code": "LOCAL",
      "brand_name": "Saudi Master",
      "cat_slug": "formwork"
    },
    {
      "id": 6,
      "classification_id": 1,
      "brand_id": 1,
      "category_id": 2,
      "sku": "SMC-PF-06",
      "slug": "piers-formwork",
      "name_en": "Bespoke Highway Pier Systems",
      "name_ar": "نظام قوالب ركائز الجسور والهامات",
      "tagline_en": "Bespoke Heavy-Gauge Steel Shuttering for Bridges and Interchange Pylons",
      "tagline_ar": "قوالب فولاذية ثقيلة مصممة خصيصاً لأعمدة الجسور العلوية وتقاطعات الطرق",
      "short_summary_en": "A customized structural steel shuttering system manufactured for casting reinforced-concrete bridge piers, viaduct columns, and flared hammerhead caps.",
      "short_summary_ar": "نظام شدات فولاذية متخصصة مصممة لصب أعمدة الجسور وركائز التقاطعات العلوية وهامات التحميل المعقدة.",
      "what_is_it_en": "Multi-segment modular steel forms engineered to match project-specific geometric curvature and cross-sectional tapers.",
      "what_is_it_ar": "قوالب فولاذية مجزأة تصنع هندسياً لتطابق المنحنيات المعمارية وزوايا الانحدار الخاصة بكل جسر.",
      "what_is_used_for_en": "High-speed rail viaducts, highway interchange flyovers, marine bridge pylons, and heavy infrastructure overpasses.",
      "what_is_used_for_ar": "جسور قطارات النقل السريع، تقاطعات الطرق السريعة العلوية، ركائز الجسور البحرية، والأنفاق المعلقة.",
      "how_does_it_work_en": "Curved panels are rigged into place around heavy reinforcing cages. Anchor ties and integral working access brackets enable safe, monolithic casting in 4m to 8m vertical segments.",
      "how_does_it_work_ar": "تثبت الألواح حول قفص التسليح وتغلق بنقاط ربط جسيمة ومنصات عمل محيطية متكاملة لصب قطاعات بارتفاعات تصل إلى 8 أمتار.",
      "key_advantages_en": [
        "Engineered FEA stress analysis for severe desert wind gust dynamics",
        "Full pre-assembly verification at Riyadh plant prior to dispatch",
        "Self-supporting tie-free options for signature architectural bridge piers",
        "Seamless compatibility with heavy shoring falsework"
      ],
      "key_advantages_ar": [
        "تحليل إجهادات هندسي متقدم لمقاومة العواصف والرياح الشديدة",
        "تجميع تجريبي واختبار مسبق في مصنع الرياض قبل الشحن للموقع",
        "خيارات تدعيم ذاتي بدون زراجين نافذة للأعمدة الأيقونية",
        "توافق تام مع أبراج التدعيم الثقيل وأنظمة أولما"
      ],
      "main_components_en": [
        "Tapered Steel Pier Shells",
        "Hammerhead Soffit Brackets",
        "Heavy Tie Rods & Walers",
        "Perimeter Working Deck",
        "Access Ladderway"
      ],
      "main_components_ar": [
        "ألواح الركيزة الفولاذية المتدرجة",
        "كوابيل هامات الجسور السفلية",
        "مسامير الشد والكمرات المقواة",
        "منصة عمل محيطية",
        "مسار سلم آمن"
      ],
      "technical_specs": {
        "steel_specification": "S355JR high-yield steel",
        "pier_height_supported": "Up to 40 m segmented",
        "lateral_pressure": "120 kN/m² hydrostatic",
        "fabrication_tolerance": "± 1.5 mm laser verified"
      },
      "sales_available": 1,
      "rental_available": 1,
      "regional_availability": [
        "KSA",
        "GCC",
        "MENA"
      ],
      "hero_image": "images/products/piers-formwork.jpg",
      "main_image": "images/products/piers-formwork.jpg",
      "drawing_url": "/assets/drawings/pier-formwork.pdf",
      "brochure_url": "/assets/brochures/sm-piers.pdf",
      "video_url": null,
      "status": "PUBLISHED",
      "featured": 1,
      "display_order": 6,
      "meta_title_en": null,
      "meta_title_ar": null,
      "meta_desc_en": null,
      "meta_desc_ar": null,
      "created_by": null,
      "updated_by": null,
      "created_at": "2026-09-28 21:12:59",
      "updated_at": "2026-09-28 21:12:59",
      "class_code": "LOCAL",
      "brand_name": "Saudi Master",
      "cat_slug": "formwork"
    },
    {
      "id": 7,
      "classification_id": 2,
      "brand_id": 2,
      "category_id": 2,
      "sku": "ULM-ORM-01",
      "slug": "ulma-formwork",
      "name_en": "ULMA ORMA Modular Formwork",
      "name_ar": "نظام شدات أولما أورما المعيارية للحوائط",
      "tagline_en": "European Benchmark for High-Efficiency Concrete Wall & Column Construction",
      "tagline_ar": "المعيار الأوروبي الرائد لشدات الحوائط والأعمدة الخرسانية عالية الكفاءة",
      "short_summary_en": "An engineered modular panel formwork system developed by ULMA in Spain, designed for rapid crane-handled forming of large concrete wall surfaces.",
      "short_summary_ar": "نظام شدات معيارية أوروبي متقدم من شركة أولما الإسبانية مخصص لصب الحوائط الكبيرة والأعمدة ورفعها بالرافعة بأقصى سرعة.",
      "what_is_it_en": "High-strength perimeter steel frame with reinforced corners enclosing 21mm Finnish birch phenolic plywood face, joined by a single-strike BFD clamp.",
      "what_is_it_ar": "إطار فولاذي عالي المقاومة بزوايا مقواة يحيط بخشب فنلندي فينولي 21 مم، يتم ربطه برابط BFD السريع بضربة واحدة.",
      "what_is_used_for_en": "High-rise building cores, shear walls, retaining structures, bridge abutments, and underground infrastructure.",
      "what_is_used_for_ar": "أبراج المباني الشاهقة، حوائط القص، الجدران الاستنادية، دعامات الجسور، ومشاريع الأنفاق والبنية التحتية.",
      "how_does_it_work_en": "Panels join rapidly with the multi-function BFD clamp which aligns, stiffens, and tightly locks adjacent panels in a single motion, handling 80 kN/m² concrete pressure.",
      "how_does_it_work_ar": "ترتبط الألواح برابط BFD متعدد الوظائف الذي يضبط المحاذاة ويشد الوصلة بحركة واحدة لتقاوم ضغط خرسانة حتى 80 كيلو نيوتن/م².",
      "key_advantages_en": [
        "Certified to EN 12812 European temporary works norms",
        "Only 2 tie rods required for 3.3m high panels",
        "BFD clamp achieves panel connection and flush alignment simultaneously",
        "Extensive rental stock available across KSA"
      ],
      "key_advantages_ar": [
        "معتمد ومطابق للمعايير الأوروبية للشدات EN 12812",
        "يتطلب مربطين فقط للارتفاع الكامل 3.3 متراً",
        "رابط BFD يحقق التوصيل والمحاذاة التامة بضغطة واحدة",
        "أسطول تأجير ضخم متاح بجميع مستودعات المملكة"
      ],
      "main_components_en": [
        "ORMA Panel Elements (3.3m & 2.7m)",
        "BFD Quick Coupling Clamps",
        "DW15 / DW20 Tie Systems",
        "Push-Pull Plumbing Props",
        "Pouring Platform Brackets"
      ],
      "main_components_ar": [
        "ألواح أورما الأساسية (3.3م و 2.7م)",
        "قمطات الربط السريع BFD",
        "مجموعة زراجين الربط DW15/20",
        "دعامات ضبط الشاقولية",
        "كوابيل منصات الصب الآمنة"
      ],
      "technical_specs": {
        "max_concrete_pressure": "80 kN/m²",
        "plywood_spec": "21 mm 100% Birch Plywood 220 g/m² film",
        "panel_heights": "3.3 m, 2.7 m, 1.2 m",
        "panel_widths": "0.3 m to 2.4 m",
        "euro_code": "EN 12812 / DIN 18218"
      },
      "sales_available": 1,
      "rental_available": 1,
      "regional_availability": [
        "KSA",
        "GCC",
        "MENA",
        "AFRICA"
      ],
      "hero_image": "images/products/ulma-formwork.jpg",
      "main_image": "images/products/ulma-formwork.jpg",
      "drawing_url": "/assets/drawings/ulma-orma.pdf",
      "brochure_url": "/assets/brochures/ulma-orma.pdf",
      "video_url": null,
      "status": "PUBLISHED",
      "featured": 1,
      "display_order": 7,
      "meta_title_en": null,
      "meta_title_ar": null,
      "meta_desc_en": null,
      "meta_desc_ar": null,
      "created_by": null,
      "updated_by": null,
      "created_at": "2026-09-28 21:12:59",
      "updated_at": "2026-09-28 21:12:59",
      "class_code": "EUROPEAN",
      "brand_name": "ULMA Construction",
      "cat_slug": "formwork"
    },
    {
      "id": 8,
      "classification_id": 2,
      "brand_id": 2,
      "category_id": 1,
      "sku": "ULM-BRIO-02",
      "slug": "ulma-brio-ringlock",
      "name_en": "ULMA BRIO Ringlock Scaffolding",
      "name_ar": "نظام سقالات أولما بريو رينج لوك متعددة الاتجاهات",
      "tagline_en": "Gold Standard European Multidirectional Scaffolding for Access & Shoring",
      "tagline_ar": "المعيار الذهبي الأوروبي للسقالات متعددة الاتجاهات للواجهات وأبراج التدعيم",
      "short_summary_en": "A certified multidirectional ringlock scaffolding system designed and certified according to European standards EN 12810-1/2 and EN 12811-1/2/3.",
      "short_summary_ar": "نظام سقالات متطور معتمد وفق أعلى المعايير الأوروبية EN 12810/12811 يوفر حلول الوصول والتدعيم الأكثر أماناً في العالم.",
      "what_is_it_en": "Standards equipped with patented 8-hole connection rosettes at 500mm spacing, accepting ledger and diagonal brace heads with captive wedge locks.",
      "what_is_it_ar": "قوائم مجهزة بقرص الوردة الحاصل على براءة اختراع بثمانية ثقوب ربط كل 500 مم، تستقبل رؤوس العوارض والمقصات بإسفين قفل ذاتي.",
      "what_is_used_for_en": "Architectural facades, petrochemical refineries, industrial boiler maintenance, complex curved structures, and public temporary pedestrian bridges.",
      "what_is_used_for_ar": "واجهات المباني المعقدة، مصافي البتروكيماويات، صيانة الغلايات الصناعية، المنشآت المنحنية، والجسور المؤقتة للمشاة.",
      "how_does_it_work_en": "Ledger cast ends slide over the rosette disc. The integrated captive steel wedge is driven through the matching opening and secured with a single hammer blow.",
      "how_does_it_work_ar": "تنزلق رؤوس العوارض فوق فتحات قرص الوردة، ويتم تثبيت الإسفين الفولاذي المدمج بضربة مطرقة محكمة تمنع الاهتزاز تحت أي أحمال.",
      "key_advantages_en": [
        "Certified under AENOR Product Certification according to EN 12810/11",
        "Supports up to 8 connections at a single node without geometric interference",
        "High leg capacity up to 75 kN when configured as heavy shoring",
        "Anti-tilt non-slip perforated steel decking"
      ],
      "key_advantages_ar": [
        "حاصل على شهادة الجودة الإسبانية والأوروبية AENOR وفق EN 12810/11",
        "ربط حتى 8 عناصر في النقطة الواحدة بزوايا متعددة بحرية تامة",
        "قدرة تحمل تصل إلى 75 كيلو نيوتن للقائم عند استخدامه كبرج تدعيم",
        "ألواح معدنية مثقبة مانعة للانزلاق ومقاومة للرياح"
      ],
      "main_components_en": [
        "BRIO Standard with Rosette",
        "BRIO Ledger with Wedge",
        "Diagonal Brace",
        "Steel Walkway Deck",
        "Aluminum Access Trapdoor Ladder",
        "Toe Boards"
      ],
      "main_components_ar": [
        "قائم بريو بقرص الوردة",
        "ذراع بريو بالإسفين المدمج",
        "مقص قطري",
        "ألواح مشايات فولاذية",
        "سلم ألومنيوم مع فتحة عبور",
        "حواجز حماية سفلية"
      ],
      "technical_specs": {
        "tube_specs": "Ø 48.3 mm x 3.2 mm S355 steel",
        "rosette_spacing": "500 mm regular interval",
        "hot_dip_galv": "≥ 75 µm thickness",
        "load_class": "Class 6 heavy industrial (6.0 kN/m²)",
        "certification": "AENOR / EN 12810 / EN 12811"
      },
      "sales_available": 1,
      "rental_available": 1,
      "regional_availability": [
        "KSA",
        "GCC",
        "MENA",
        "AFRICA"
      ],
      "hero_image": "images/products/ulma-brio-ringlock.jpg",
      "main_image": "images/products/ulma-brio-ringlock.jpg",
      "drawing_url": "/assets/drawings/ulma-brio.pdf",
      "brochure_url": "/assets/brochures/ulma-brio.pdf",
      "video_url": null,
      "status": "PUBLISHED",
      "featured": 1,
      "display_order": 8,
      "meta_title_en": null,
      "meta_title_ar": null,
      "meta_desc_en": null,
      "meta_desc_ar": null,
      "created_by": null,
      "updated_by": null,
      "created_at": "2026-09-28 21:12:59",
      "updated_at": "2026-09-28 21:12:59",
      "class_code": "EUROPEAN",
      "brand_name": "ULMA Construction",
      "cat_slug": "scaffolding"
    },
    {
      "id": 9,
      "classification_id": 2,
      "brand_id": 2,
      "category_id": 3,
      "sku": "ULM-MK-03",
      "slug": "ulma-heavy-shoring",
      "name_en": "ULMA Heavy Shoring Systems (MK / T-500)",
      "name_ar": "أبراج التدعيم الثقيل أولما إم كيه و تي-500",
      "tagline_en": "Extreme-Capacity Structural Falsework Towers Supporting Up to 500 kN Per Leg",
      "tagline_ar": "أبراج تدعيم إنشائية جبارة تتحمل حتى 500 كيلو نيوتن لكل قائم للجسور الكبرى",
      "short_summary_en": "A high-load modular shoring and truss falsework system engineered for heavy civil concrete structures, viaduct spans, and deep transfer slabs.",
      "short_summary_ar": "نظام أبراج تدعيم ثقيل فائق القدرة مصمم للأعمال الإنشائية الكبرى وأسقف الجسور والبحور الخرسانية الضخمة.",
      "what_is_it_en": "Modular MK structural steel walers combined into independent towers, gantry falsework frames, or launching carriages.",
      "what_is_it_ar": "كمرات فولاذية إنشائية متعددة الاستخدامات تشكل أبراجاً مستقلة أو بوابات تدعيم مفتوحة لحركة المرور السفلية.",
      "what_is_used_for_en": "Balanced cantilever bridges, post-tensioned flyover spans, mega-transfer beam supports, and tunnel portal casting.",
      "what_is_used_for_ar": "جسور الكابول المتوازن، أسقف التقاطعات مسبقة الإجهاد، كمرات التحويل الخرسانية العملاقة، وبوابات الأنفاق.",
      "how_does_it_work_en": "MK walers bolt together via standardized high-tensile connection plates. Hydraulic jacks at base or head allow controlled pre-loading and millimeter-accurate post-pour release.",
      "how_does_it_work_ar": "ترتبط كمرات MK بصفائح براغي عالية المقاومة، وتتيح المكابس الهيدروليكية التحكم الدقيق في الشد المسبق والفك السلس للشدة.",
      "key_advantages_en": [
        "Enormous load capacity from 250 kN up to 500 kN per shoring column",
        "Allows large traffic clearance spans underneath without closing live roads",
        "Complete structural calculation package signed by European and Saudi PEs",
        "Fully compatible with ULMA formwork decks"
      ],
      "key_advantages_ar": [
        "قدرة تحمل فائقة تبدأ من 250 إلى 500 كيلو نيوتن للقائم الواحد",
        "تتيح فتح بحور عريضة لمرور السيارات أثناء الصب دون إغلاق الطرق",
        "حسابات إنشائية متكاملة معتمدة من مهندسين معتمدين بأوروبا والسعودية",
        "توافق هندسي كامل مع أنظمة شدات أسطح أولما"
      ],
      "main_components_en": [
        "MK Heavy Waler Beams",
        "Spindle Screw Jacks",
        "High-Load Base Plates",
        "Diagonal Bracing Trusses",
        "Hydraulic Lowering Units"
      ],
      "main_components_ar": [
        "كمرات تدعيم MK الإنشائية",
        "روافع لولبية ثقيلة",
        "قواعد ارتكاز عالية التحمل",
        "جمالونات تثبيت قطرية",
        "وحدات تخفيض هيدروليكية"
      ],
      "technical_specs": {
        "leg_load_capacity": "Up to 500 kN / leg",
        "waler_profile": "Double UPN rolled channels back-to-back",
        "steel_quality": "S355 Structural Steel",
        "certifications": "EN 12812 / Eurocode 3"
      },
      "sales_available": 1,
      "rental_available": 1,
      "regional_availability": [
        "KSA",
        "GCC",
        "MENA"
      ],
      "hero_image": "images/products/ulma-heavy-shoring.jpg",
      "main_image": "images/products/ulma-heavy-shoring.jpg",
      "drawing_url": "/assets/drawings/ulma-mk.pdf",
      "brochure_url": "/assets/brochures/ulma-mk.pdf",
      "video_url": null,
      "status": "PUBLISHED",
      "featured": 1,
      "display_order": 9,
      "meta_title_en": null,
      "meta_title_ar": null,
      "meta_desc_en": null,
      "meta_desc_ar": null,
      "created_by": null,
      "updated_by": null,
      "created_at": "2026-09-28 21:12:59",
      "updated_at": "2026-09-28 21:12:59",
      "class_code": "EUROPEAN",
      "brand_name": "ULMA Construction",
      "cat_slug": "heavy-shoring"
    },
    {
      "id": 10,
      "classification_id": 2,
      "brand_id": 2,
      "category_id": 4,
      "sku": "ULM-CLB-04",
      "slug": "specialized-formwork",
      "name_en": "Specialized Climbing & Hydraulic Systems (ATR)",
      "name_ar": "أنظمة الشدات المتخصصة والتسلق الهيدروليكي الآلي",
      "tagline_en": "Crane-Independent Hydraulic Self-Climbing Formwork for Mega-Tower Cores",
      "tagline_ar": "شدات تسلق ذاتي هيدروليكية مستقلة عن الرافعة البرجية للأبراج الشاهقة",
      "short_summary_en": "Crane-free hydraulic climbing systems and rail-guided perimeter safety screens designed for ultra-tall skyscraper towers and suspension pylons.",
      "short_summary_ar": "منظومة تسلق ذاتية هيدروليكية بالكامل وشاشات حماية محيطية موجهة بمسارات سكك مصممة للأبراج شاهقة الارتفاع وأعمدة الجسور.",
      "what_is_it_en": "Continuous mast rails anchored to cast concrete sleeves with synchronized hydraulic climbing cylinders moving multi-story platforms simultaneously.",
      "what_is_it_ar": "سكك توجيه مستمرة مثبتة بالخرسانة المتصلبة مع مكابس هيدروليكية متزامنة ترفع منصات متعددة الطوابق بلمسة زر واحدة.",
      "what_is_used_for_en": "Skyscrapers exceeding 40 floors, high-wind airport control towers, telecommunications obelisks, and deep dam pylons.",
      "what_is_used_for_ar": "ناطحات السحاب التي تتجاوز 40 طابقاً، أبراج المراقبة الجوية، الصوامع الشاهقة، وركائز السدود الضخمة.",
      "how_does_it_work_en": "Hydraulic power units advance the climbing rails upward into fresh anchor shoes, followed by the entire platform assembly in an automated cycle.",
      "how_does_it_work_ar": "تقوم المحطات الهيدروليكية برفع سكك التوجيه نحو مرابط التثبيت الجديدة، تليها المنصة والشدات كاملة في دورة رفع منتظمة لا تتعدى 20 دقيقة.",
      "key_advantages_en": [
        "Operates independently of tower crane availability, saving critical crane time",
        "Full weather and wind enclosure protecting crews up to extreme elevations",
        "Heavy concrete placing boom can be mounted directly onto the climbing mast",
        "Zero drop hazard with continuous mechanical pawl locking"
      ],
      "key_advantages_ar": [
        "استقلالية تامة عن الرافعات البرجية مما يوفر ساعات تشغيل الرافعة الحيوية",
        "حماية محيطية كاملة من الرياح والأتربة تضمن سلامة العمال في الارتفاعات",
        "إمكانية تثبيت مضخة صب الخرسانة الذراعية مباشرة على صاري التسلق",
        "انعدام مخاطر السقوط بفضل سقاطات القفل الميكانيكي المستمر"
      ],
      "main_components_en": [
        "ATR Hydraulic Cylinders",
        "Guide Climbing Rails",
        "Anchor Cone Receptacles",
        "Multi-Tiered Work Platforms",
        "HWS Wind Protection Screens"
      ],
      "main_components_ar": [
        "اسطوانات التسلق الهيدروليكية ATR",
        "سكك التوجيه الرأسية",
        "مخاريط التثبيت في الخرسانة",
        "منصات العمل متعددة المستويات",
        "شاشات حماية الرياح HWS"
      ],
      "technical_specs": {
        "cylinder_capacity": "100 kN lifting force",
        "stroke_length": "4.0 m single push",
        "wind_resistance": "Operational up to 72 km/h wind speeds",
        "enclosure": "Corrugated steel or perforated mesh"
      },
      "sales_available": 1,
      "rental_available": 1,
      "regional_availability": [
        "KSA",
        "GCC"
      ],
      "hero_image": "images/products/specialized-formwork.jpg",
      "main_image": "images/products/specialized-formwork.jpg",
      "drawing_url": "/assets/drawings/ulma-atr.pdf",
      "brochure_url": "/assets/brochures/ulma-atr.pdf",
      "video_url": null,
      "status": "PUBLISHED",
      "featured": 0,
      "display_order": 10,
      "meta_title_en": null,
      "meta_title_ar": null,
      "meta_desc_en": null,
      "meta_desc_ar": null,
      "created_by": null,
      "updated_by": null,
      "created_at": "2026-09-28 21:12:59",
      "updated_at": "2026-09-28 21:12:59",
      "class_code": "EUROPEAN",
      "brand_name": "ULMA Construction",
      "cat_slug": "specialized-climbing"
    },
    {
      "id": 11,
      "classification_id": 2,
      "brand_id": 2,
      "category_id": 4,
      "sku": "ULM-ENG-05",
      "slug": "project-specific-engineering",
      "name_en": "Project-Specific Engineered Solutions",
      "name_ar": "الحلول الهندسية المخصصة للمشاريع الكبرى",
      "tagline_en": "Turnkey Finite Element Analysis, BIM Coordination, and Custom Structural Weldments",
      "tagline_ar": "دراسات إجهادات العناصر المحدودة FEA ونمذجة BIM وقطع تصنيع فولاذية مخصصة",
      "short_summary_en": "A comprehensive temporary works engineering service integrating 3D BIM clash detection, structural static calculations, and hybrid European-Saudi equipment assemblies.",
      "short_summary_ar": "خدمة هندسية متكاملة للشدات المؤقتة تجمع بين النمذجة ثلاثية الأبعاد وفحص التعارضات والحسابات الإنشائية للحلول الهجينة.",
      "what_is_it_en": "High-density structural calculations paired with custom fabricated transition brackets that bridge standard ULMA systems with site-specific architectural geometry.",
      "what_is_it_ar": "حسابات إجهادات دقيقة مع وصلات تصنيع فولاذية خاصة تدمج أنظمة أولما القياسية مع الأشكال المعمارية المعقدة للمشروع.",
      "what_is_used_for_en": "Iconic cultural pavilions, stadium cantilevered canopies, tunnel carriage shuttering, and deep station cut-and-cover excavations.",
      "what_is_used_for_ar": "المتاحف والمراكز الثقافية الأيقونية، مظلات الملاعب الرياضية، عربات صب الأنفاق، ومحطات المترو العميقة.",
      "how_does_it_work_en": "Engineers analyze structural drawings, build parametric 3D models in Navisworks/Revit, run FEA load simulations, and fabricate custom connection nodes at our Riyadh center.",
      "how_does_it_work_ar": "يقوم مهندسونا بتحليل المخططات، بناء نماذج ثلاثية الأبعاد ومحاكاة الأحمال بدقة، وتصنيع وصلات الربط الخاصة في مجمع الرياض.",
      "key_advantages_en": [
        "Full compliance with Saudi Building Code (SBC) and European Eurocodes",
        "Zero-clash digital twin submittals for tier-1 consultants",
        "PE-stamped calculation books accepted across NEOM, Red Sea, and Qiddiya",
        "On-site resident engineer supervision during erection"
      ],
      "key_advantages_ar": [
        "مطابقة تامة لكود البناء السعودي (SBC) والكود الأوروبي Eurocodes",
        "مخططات توأمة رقمية معتمدة خالية من التعارضات للاستشاريين",
        "دفاتر حسابات إنشائية معتمدة في نيوم والبحر الأحمر والقدية",
        "تواجد مهندس مقيم للإشراف الميداني أثناء التركيب"
      ],
      "main_components_en": [
        "FEA Stress Calculation Book",
        "3D BIM LOD 400 Erection Model",
        "Custom Steel Transition Welds",
        "Step-by-Step Method Statement"
      ],
      "main_components_ar": [
        "دفتر حسابات الإجهادات FEA",
        "نموذج تركيب BIM LOD 400",
        "وصلات تحويل فولاذية مخصصة",
        "دليل تسلسل التركيب التفصيلي"
      ],
      "technical_specs": {
        "software_suite": "Autodesk Revit, Navisworks, RSTAB, Dlubal FEA",
        "bim_standard": "ISO 19650 / LOD 400",
        "pe_stamp": "Licensed Saudi Council of Engineers (SCE)",
        "wind_analysis": "Desert dynamic wind load simulation"
      },
      "sales_available": 1,
      "rental_available": 0,
      "regional_availability": [
        "KSA",
        "GCC",
        "MENA",
        "AFRICA"
      ],
      "hero_image": "images/products/project-specific-engineering.jpg",
      "main_image": "images/products/project-specific-engineering.jpg",
      "drawing_url": "/assets/drawings/custom-engineering.pdf",
      "brochure_url": "/assets/brochures/custom-engineering.pdf",
      "video_url": null,
      "status": "PUBLISHED",
      "featured": 0,
      "display_order": 11,
      "meta_title_en": null,
      "meta_title_ar": null,
      "meta_desc_en": null,
      "meta_desc_ar": null,
      "created_by": null,
      "updated_by": null,
      "created_at": "2026-09-28 21:12:59",
      "updated_at": "2026-09-28 21:12:59",
      "class_code": "EUROPEAN",
      "brand_name": "ULMA Construction",
      "cat_slug": "specialized-climbing"
    },
    {
      "id": 12,
      "classification_id": 2,
      "brand_id": 2,
      "category_id": 1,
      "sku": "ULM-WPF-06",
      "slug": "circular-working-platforms",
      "name_en": "Working Platforms & Circular Access (SGF / KSP)",
      "name_ar": "منصات العمل المحيطية والوصول للمنشآت الدائرية",
      "tagline_en": "High-Security Perimeter Staging and Suspended Brackets for Silos and Storage Tanks",
      "tagline_ar": "منصات محيطية معلقة عالية الأمان لخزانات التخزين والصوامع والأعمدة العالية",
      "short_summary_en": "Modular perimeter brackets and suspended staging platforms designed to wrap circular storage tanks, flared bridge piers, and silo perimeters with zero fall hazard.",
      "short_summary_ar": "كوابيل ومنصات عمل محيطية معلقة مصممة لتطويق الخزانات الدائرية والصوامع وأعمدة الجسور بأقصى درجات الأمان.",
      "what_is_it_en": "Heavy-duty cantilevered brackets anchoring directly into prior pour tie-rod cones with fully integrated perimeter mesh screens and toe boards.",
      "what_is_it_ar": "كوابيل كابولية تثبت مباشرة في ثقوب زراجين الصبة السابقة مع شباك حماية محيطية وألواح حماية القدمين.",
      "what_is_used_for_en": "Wastewater clarifier tanks, cryogenic LNG spherical storage, grain silos, and stepped bridge pylon pours.",
      "what_is_used_for_ar": "خزانات محطات معالجة المياه، خزانات الغاز المسال، صوامع الغلال، والأعمدة الخرسانية المتدرجة.",
      "how_does_it_work_en": "Brackets hang from anchor cones placed in previous concrete lifts. Workers assemble safe continuous circular walkways that follow the structure radius smoothly.",
      "how_does_it_work_ar": "تعلق الكوابيل بمخاريط التثبيت في الخرسانة السابقة، وتكون ممرات مشاة دائرية مستمرة تطابق نصف قطر المنشأة بدون فجوات خطرة.",
      "key_advantages_en": [
        "Completely enclosed work zones with fall arrest anchor rings",
        "Adjustable bracket inclination compensates for batter angles up to 20°",
        "Hot-dip galvanized components withstand harsh coastal and industrial environments",
        "OSHA and Saudi Civil Defense safety compliance"
      ],
      "key_advantages_ar": [
        "مناطق عمل مغلقة بالكامل مع نقاط تثبيت معتمدة لأحزمة الأمان",
        "زاوية ميلان قابلة للتعديل حتى 20 درجة للحوائط المائلة",
        "جلفنة بالغمس الساخن تقاوم التآكل في البيئات الساحلية والصناعية",
        "مطابقة تامة لاشتراطات أوشا والدفاع المدني السعودي"
      ],
      "main_components_en": [
        "SGF Climbing Brackets",
        "Heavy Anchor Cones",
        "Perimeter Safety Handrails",
        "Non-Slip Circular Deck Infill",
        "Integrated Hoist Arm"
      ],
      "main_components_ar": [
        "كوابيل التسلق SGF",
        "مخاريط التثبيت الثقيلة",
        "درابزينات حماية محيطية",
        "ألواح خشبية/معدنية مخصصة للمنحنيات",
        "ذراع رفع مواد يدوي"
      ],
      "technical_specs": {
        "permissible_live_load": "Class 4 (3.0 kN/m²)",
        "platform_width": "1.8 m to 2.2 m wide deck",
        "max_angle_inclination": "± 20° vertical slope",
        "safety_standard": "EN 12811-1 / OSHA 1926"
      },
      "sales_available": 1,
      "rental_available": 1,
      "regional_availability": [
        "KSA",
        "GCC",
        "MENA"
      ],
      "hero_image": "images/products/circular-working-platforms.jpg",
      "main_image": "images/products/circular-working-platforms.jpg",
      "drawing_url": "/assets/drawings/ulma-platforms.pdf",
      "brochure_url": "/assets/brochures/ulma-platforms.pdf",
      "video_url": null,
      "status": "PUBLISHED",
      "featured": 0,
      "display_order": 12,
      "meta_title_en": null,
      "meta_title_ar": null,
      "meta_desc_en": null,
      "meta_desc_ar": null,
      "created_by": null,
      "updated_by": null,
      "created_at": "2026-09-28 21:12:59",
      "updated_at": "2026-09-28 21:12:59",
      "class_code": "EUROPEAN",
      "brand_name": "ULMA Construction",
      "cat_slug": "scaffolding"
    }
  ],
  "processes": [
    {
      "id": 1,
      "step_number": 1,
      "name_en": "Material Receiving & Spectro QA",
      "name_ar": "فحص واختبار المواد الخام",
      "summary_en": "Certified structural steel tubes (S275/S355) undergo optical spectrometry and tensile stress testing upon arrival.",
      "summary_ar": "تخضع أنابيب وصفائح الفولاذ الإنشائي لاختبارات التحليل الطيفي ومقاومة الشد فور وصولها للتأكد من مطابقتها التامة.",
      "details_en": "Certified structural steel tubes (S275/S355) undergo optical spectrometry and tensile stress testing upon arrival.",
      "details_ar": "تخضع أنابيب وصفائح الفولاذ الإنشائي لاختبارات التحليل الطيفي ومقاومة الشد فور وصولها للتأكد من مطابقتها التامة.",
      "image_url": "images/manufacturing/mfg-material-receiving.jpg",
      "step_tag": "Step 01: Raw Materials",
      "hero_image": "images/manufacturing/mfg-material-receiving.jpg"
    },
    {
      "id": 2,
      "step_number": 2,
      "name_en": "CNC High-Tension Profiling",
      "name_ar": "القص والتشكيل الرقمي CNC",
      "summary_en": "Sub-millimeter automated laser and rotary tube cutting ensuring accurate cuplock node placements and clean bevel angles.",
      "summary_ar": "قص ليزري رقمي دقيق للأنابيب والصفائح يضمن تمركز عقد التثبيت بدقة متناهية وزوايا لحام مثالية.",
      "details_en": "Sub-millimeter automated laser and rotary tube cutting ensuring accurate cuplock node placements and clean bevel angles.",
      "details_ar": "قص ليزري رقمي دقيق للأنابيب والصفائح يضمن تمركز عقد التثبيت بدقة متناهية وزوايا لحام مثالية.",
      "image_url": "images/manufacturing/mfg-cnc-profiling.jpg",
      "step_tag": "Step 02: CNC Profiling",
      "hero_image": "images/manufacturing/mfg-cnc-profiling.jpg"
    },
    {
      "id": 3,
      "step_number": 3,
      "name_en": "Multi-Axis Robotic Welding",
      "name_ar": "اللحام الآلي الروبوتي المتطور",
      "summary_en": "Automated welding cells delivering full-penetration seams tested against cyclic vibration and extreme load concentrations.",
      "summary_ar": "محطات لحام روبوتية متعددة المحاور تضمن درزات لحام متجانسة وعميقة ومقاومة للاهتزازات والأحمال العالية.",
      "details_en": "Automated welding cells delivering full-penetration seams tested against cyclic vibration and extreme load concentrations.",
      "details_ar": "محطات لحام روبوتية متعددة المحاور تضمن درزات لحام متجانسة وعميقة ومقاومة للاهتزازات والأحمال العالية.",
      "image_url": "images/manufacturing/mfg-robotic-welding.jpg",
      "step_tag": "Step 03: Robotic Welding",
      "hero_image": "images/manufacturing/mfg-robotic-welding.jpg"
    },
    {
      "id": 4,
      "step_number": 4,
      "name_en": "Thermal Dip Galvanizing & Coating",
      "name_ar": "الجلفنة بالغمس الساخن والطلاء",
      "summary_en": "Immersion in molten zinc baths (≥ 65-85 µm) providing decades of corrosion resistance in aggressive desert and marine environments.",
      "summary_ar": "غمس القطع في أحواض الزنك المنصهر لتوفير طبقة جلفنة متينة تقاوم التآكل في البيئات البحرية والصحراوية القاسية.",
      "details_en": "Immersion in molten zinc baths (≥ 65-85 µm) providing decades of corrosion resistance in aggressive desert and marine environments.",
      "details_ar": "غمس القطع في أحواض الزنك المنصهر لتوفير طبقة جلفنة متينة تقاوم التآكل في البيئات البحرية والصحراوية القاسية.",
      "image_url": "images/manufacturing/mfg-hot-dip-galvanizing.jpg",
      "step_tag": "Step 04: Hot-Dip Galvanizing",
      "hero_image": "images/manufacturing/mfg-hot-dip-galvanizing.jpg"
    },
    {
      "id": 5,
      "step_number": 5,
      "name_en": "Hydraulic Load Proof Testing",
      "name_ar": "اختبار التحميل الهيدروليكي والمعايرة",
      "summary_en": "Calibrated hydraulic rigs perform destructive and non-destructive load tests ensuring compliance with SASO and European norms.",
      "summary_ar": "منصات هيدروليكية متطورة تجري اختبارات التحميل الميكانيكية وإثبات مقاومة التشوه لضمان السلامة الميدانية 100%.",
      "details_en": "Calibrated hydraulic rigs perform destructive and non-destructive load tests ensuring compliance with SASO and European norms.",
      "details_ar": "منصات هيدروليكية متطورة تجري اختبارات التحميل الميكانيكية وإثبات مقاومة التشوه لضمان السلامة الميدانية 100%.",
      "image_url": "images/manufacturing/mfg-hydraulic-load-testing.jpg",
      "step_tag": "Step 05: Proof Loading",
      "hero_image": "images/manufacturing/mfg-hydraulic-load-testing.jpg"
    },
    {
      "id": 6,
      "step_number": 6,
      "name_en": "Barcoded Staging & Rapid Dispatch",
      "name_ar": "التجهيز الرقمي والشحن الفوري",
      "summary_en": "Individual batches are barcoded, certified, strapped, and dispatched directly onto dedicated heavy logistics flatbeds.",
      "summary_ar": "ترميز الشحنات بباركود رقمي يتيح التتبع اللوجستي وشحنها الفوري على أسطول الشاحنات للمشاريع في غضون ساعات.",
      "details_en": "Individual batches are barcoded, certified, strapped, and dispatched directly onto dedicated heavy logistics flatbeds.",
      "details_ar": "ترميز الشحنات بباركود رقمي يتيح التتبع اللوجستي وشحنها الفوري على أسطول الشاحنات للمشاريع في غضون ساعات.",
      "image_url": "images/manufacturing/mfg-rapid-dispatch.jpg",
      "step_tag": "Step 06: Rapid Dispatch",
      "hero_image": "images/manufacturing/mfg-rapid-dispatch.jpg"
    }
  ],
  "projects": [
    {
      "id": 1,
      "name_en": "NEOM Spine Rail High-Speed Viaduct",
      "name_ar": "جسر قطار نيوم فائق السرعة",
      "slug": "neom-spine-rail-viaduct",
      "location_en": "NEOM (The Line Sector 04), Saudi Arabia",
      "location_ar": "نيوم (قطاع ذا لاين 04)، المملكة العربية السعودية",
      "region_code": "KSA",
      "industry_en": "Rail & High-Speed Transit",
      "industry_ar": "قطارات النقل السريع والبنية التحتية",
      "hero_image": "images/projects/neom-spine-viaduct.jpg",
      "summary_en": "Turnkey falsework and pier formwork package for monumental 32m high bridge supports in extreme desert canyon topography.",
      "summary_ar": "حزمة متكاملة للتدعيم الثقيل وشدات الأعمدة لجسور بارتفاع 32 متراً في التضاريس الجبلية الوعرة بنيوم.",
      "challenge_en": "Contractor required monolithic casting of 1,400 kN hammerhead caps while resisting 85 km/h desert crosswinds without crane availability delays.",
      "challenge_ar": "طلب المقاول صب هامات الجسور العملاقة بكتلة 1400 كيلو نيوتن ومقاومة رياح شديدة تصل لـ 85 كم/ساعة دون تأخير الرافعات.",
      "solution_en": "Saudi Master engineered a hybrid assembly pairing locally fabricated steel pier shutters with ULMA MK heavy shoring towers.",
      "solution_ar": "قامت شركة الماستر السعودي بتصميم حل هجين يجمع قوالب الأعمدة المصنعة محلياً مع أبراج التدعيم الثقيل ULMA MK.",
      "execution_en": "Continuous 24/7 on-site technical supervision ensured all 24 bridge spans were placed on time with 0-clash Navisworks verification.",
      "execution_ar": "إشراف هندسي متواصل على مدار الساعة مكن من إنجاز 24 بحراً بنجاح وبأعلى معايير الدقة والسلامة.",
      "results_en": "Zero safety incidents recorded across 180,000 man-hours; pour cycle accelerated by 4 days per segment.",
      "results_ar": "صفر حوادث سلامة عبر 180,000 ساعة عمل، مع تسريع دورة الصب بـ 4 أيام لكل قطاع.",
      "key_metrics": "[{\"label\": \"Total Pier Height\", \"value\": \"32 meters\"}, {\"label\": \"Concrete Volume\", \"value\": \"45,000 m\\u00b3\"}, {\"label\": \"Cycle Speed\", \"value\": \"6 days/pier\"}]",
      "gallery": "[\"images/projects/neom-spine-viaduct.jpg\"]",
      "status": "PUBLISHED",
      "featured": 1,
      "display_order": 0,
      "created_at": "2026-09-28 21:12:59",
      "updated_at": "2026-09-28 21:12:59",
      "metrics": [
        {
          "label": "Total Pier Height",
          "value": "32 meters"
        },
        {
          "label": "Concrete Volume",
          "value": "45,000 m³"
        },
        {
          "label": "Cycle Speed",
          "value": "6 days/pier"
        }
      ]
    },
    {
      "id": 2,
      "name_en": "Riyadh Metro Line 03 Elevated Interchange",
      "name_ar": "محطة تقاطع مترو الرياض المسار 3",
      "slug": "riyadh-metro-line-03",
      "location_en": "Riyadh, Saudi Arabia",
      "location_ar": "الرياض، المملكة العربية السعودية",
      "region_code": "KSA",
      "industry_en": "Urban Transit & Metros",
      "industry_ar": "قطارات النقل الحضري والمترو",
      "hero_image": "images/projects/infrastructure-bridge.jpg",
      "summary_en": "Heavy Cuplock shoring and bespoke steel circular column formwork across central Riyadh urban corridors.",
      "summary_ar": "سقالات تدعيم كابلوك ثقيلة وقوالب أعمدة دائرية مخصصة لمسارات التقاطعات الحيوية بمترو الرياض.",
      "challenge_en": "High-density vehicular traffic below required zero ground deflection and immediate clearance opening.",
      "challenge_ar": "حركة المرور الكثيفة أسفل الجسر تطلبت فتح مسارات الطريق دون أي إغلاق مع ثبات هندسي مطلق.",
      "solution_en": "Supplied 35,000 m² of Cuplock rental falsework with calibrated drop-heads enabling early stripping in 72 hours.",
      "solution_ar": "توريد 35 ألف متر مربع من سقالات الكابلوك مع رؤوس إسقاط سريعة أتاحت فك الشدة خلال 72 ساعة فقط.",
      "execution_en": "Delivered from our Riyadh central yard in night shifts with zero traffic disruption.",
      "execution_ar": "تم التوريد عبر فترات ليلية من مستودع الرياض لتفادي أي ازدحام مروري.",
      "results_en": "Completed 2 weeks ahead of target schedule; client awarded follow-up substation contracts.",
      "results_ar": "اكتمل العمل قبل أسبوعين من الموعد المحدد واعتمدت الهيئة أنظمتنا للمشاريع اللاحقة.",
      "key_metrics": "[{\"label\": \"Shoring Fleet\", \"value\": \"35,000 m\\u00b2\"}, {\"label\": \"Columns Cast\", \"value\": \"180 circular\"}, {\"label\": \"Striking Time\", \"value\": \"72 hours\"}]",
      "gallery": "[\"images/projects/infrastructure-bridge.jpg\"]",
      "status": "PUBLISHED",
      "featured": 1,
      "display_order": 0,
      "created_at": "2026-09-28 21:12:59",
      "updated_at": "2026-09-28 21:12:59",
      "metrics": [
        {
          "label": "Shoring Fleet",
          "value": "35,000 m²"
        },
        {
          "label": "Columns Cast",
          "value": "180 circular"
        },
        {
          "label": "Striking Time",
          "value": "72 hours"
        }
      ]
    },
    {
      "id": 3,
      "name_en": "The Red Sea Coastal Resort & Marine Gateway",
      "name_ar": "منتجع البحر الأحمر وبوابة المارينا",
      "slug": "red-sea-coastal-resort",
      "location_en": "Red Sea Destination, Saudi Arabia",
      "location_ar": "وجهة البحر الأحمر، المملكة العربية السعودية",
      "region_code": "KSA",
      "industry_en": "Luxury Hospitality & Marine",
      "industry_ar": "الضيافة الفاخرة والمنشآت البحرية",
      "hero_image": "images/projects/coastal-maritime-terminus.jpg",
      "summary_en": "Architectural Fair-Faced Concrete Wall Formwork using ULMA ORMA and coastal-grade galvanized BRIO access.",
      "summary_ar": "صب حوائط معمارية فائقة النعومة باستخدام شدات أولما أورما وسقالات بريو المقاومة للملوحة البحرية.",
      "challenge_en": "Ultra-strict architectural finish criteria requiring zero bubble defects and marine corrosion protection.",
      "challenge_ar": "معايير معمارية صارمة جداً لأسطح الخرسانة الظاهرة ومقاومة عالية للتآكل في البيئة البحرية الرطبة.",
      "solution_en": "Deployed ULMA ORMA with premium birch plywood and SASO-certified hot-dip galvanized BRIO platforms.",
      "solution_ar": "استخدام ألواح أورما بخشب فنلندي نخب أول وسقالات بريو مجلفنة بالغمس الساخن ≥ 75 ميكرون.",
      "execution_en": "Field engineers audited plywood face sealing and tie-rod alignments before every pour.",
      "execution_ar": "فحص دقيق لمفاصل الألواح ومسامير التثبيت لضمان مظهر معماري متناسق وبراق.",
      "results_en": "Received Architectural Excellence commendation from the development authority.",
      "results_ar": "حصل المشروع على إشادة هيئة تطوير البحر الأحمر للتميز في جودة الخرسانة الظاهرة.",
      "key_metrics": "[{\"label\": \"Surface Finish\", \"value\": \"Architectural Class A\"}, {\"label\": \"Marine HDG\", \"value\": \"\\u2265 75 \\u00b5m\"}, {\"label\": \"Rebar Coverage\", \"value\": \"100% Plumb\"}]",
      "gallery": "[\"images/projects/coastal-maritime-terminus.jpg\"]",
      "status": "PUBLISHED",
      "featured": 1,
      "display_order": 0,
      "created_at": "2026-09-28 21:12:59",
      "updated_at": "2026-09-28 21:12:59",
      "metrics": [
        {
          "label": "Surface Finish",
          "value": "Architectural Class A"
        },
        {
          "label": "Marine HDG",
          "value": "≥ 75 µm"
        },
        {
          "label": "Rebar Coverage",
          "value": "100% Plumb"
        }
      ]
    },
    {
      "id": 4,
      "name_en": "Qiddiya Speed Park Viaduct & Retaining Complex",
      "name_ar": "مجمع جسور وحوائط حلبة السرعة بالقدية",
      "slug": "qiddiya-speed-park",
      "location_en": "Qiddiya Entertainment City, Riyadh, KSA",
      "location_ar": "مدينة القدية الترفيهية، الرياض، المملكة العربية السعودية",
      "region_code": "KSA",
      "industry_en": "Heavy Civil & Sports Mega-Infrastructure",
      "industry_ar": "المنشآت الرياضية الكبرى والهندسة المدنية",
      "hero_image": "images/projects/qiddiya-retaining-complex.jpg",
      "summary_en": "Heavy fabricated Grinder steel shutters and heavy MK falsework for massive 18m retaining walls.",
      "summary_ar": "شدات جريندر الفولاذية الثقيلة وأبراج MK لجدران استنادية عملاقة بارتفاع 18 متراً.",
      "challenge_en": "High retaining forces in mountainous terrain with extreme thermal fluctuations from 5°C to 48°C.",
      "challenge_ar": "ضغوط استنادية هائلة في جبال القدية مع فروقات حرارية صحراوية حادة بين الصيف والشتاء.",
      "solution_en": "Fabricated extra-rigid all-steel waler shutters in our Riyadh plant coupled with MK structural braces.",
      "solution_ar": "تصنيع شدات فولاذية جسيمة بمصنعنا بالرياض لتقاوم الضغوط دون تمدد أو انحناء.",
      "execution_en": "Night-time continuous concrete placing executed under direct supervision of our technical team.",
      "execution_ar": "صب ليلي مستمر تحت إشراف مهندسينا لضمان استقرار الخرسانة تحت درجات الحرارة المثالية.",
      "results_en": "Wall poured to exact millimeter line; zero remediations or grinding required.",
      "results_ar": "تحقيق استقامة تامة للجدار بدون الحاجة لأي معالجات لاحقة، وتسليم المشروع وفق الجدول المعتمد.",
      "key_metrics": "[{\"label\": \"Retaining Height\", \"value\": \"18 meters\"}, {\"label\": \"Hydrostatic Load\", \"value\": \"90 kN/m\\u00b2\"}, {\"label\": \"Wall Length\", \"value\": \"1.2 km\"}]",
      "gallery": "[\"images/projects/qiddiya-retaining-complex.jpg\"]",
      "status": "PUBLISHED",
      "featured": 1,
      "display_order": 0,
      "created_at": "2026-09-28 21:12:59",
      "updated_at": "2026-09-28 21:12:59",
      "metrics": [
        {
          "label": "Retaining Height",
          "value": "18 meters"
        },
        {
          "label": "Hydrostatic Load",
          "value": "90 kN/m²"
        },
        {
          "label": "Wall Length",
          "value": "1.2 km"
        }
      ]
    }
  ],
  "services": [
    {
      "id": 1,
      "slug": "design",
      "name_en": "Engineering & Structural Design",
      "name_ar": "التصميم الهندسي والحسابات الإنشائية",
      "summary_en": "Certified structural calculations, FEA load analysis, and 3D BIM coordination strictly adhering to the Saudi Building Code (SBC).",
      "summary_ar": "حسابات إنشائية معتمدة، تحليل إجهادات العناصر المحدودة FEA، ونمذجة ثلاثية الأبعاد BIM مطابقة لكود البناء السعودي.",
      "description_en": "Our Riyadh-based engineering department delivers turnkey temporary works solutions: from preliminary concept sketches through PE-stamped calculation books, LOD 400 erection models, and clash-detection audits accepted by tier-1 gigaproject consultants.",
      "description_ar": "يقدم فريقنا الهندسي بالرياض حلولاً متكاملة للشدات المؤقتة: من المخططات الأولية حتى دفاتر الحسابات المعتمدة ونماذج LOD 400 المقبولة في أكبر المشاريع.",
      "icon_name": "architecture",
      "image_url": "images/services/design-build.jpg",
      "display_order": 1,
      "is_active": 1
    },
    {
      "id": 2,
      "slug": "supply",
      "name_en": "Material Supply & Logistics",
      "name_ar": "التوريد اللوجستي وإدارة المخزون",
      "summary_en": "Rapid mobilization from massive stockyards in Riyadh, Jeddah, and Dammam with flatbed fleet delivery within 24 to 48 hours.",
      "summary_ar": "توريد فوري من مستودعاتنا بالرياض وجدة والدمام عبر أسطولنا اللوجستي خلال 24 إلى 48 ساعة.",
      "description_en": "With over 120,000 meters of vertical scaffolding and 60,000 m² of certified formwork in reserve, Saudi Master guarantees zero site delay. All shipments are barcode-staged and batch-tracked.",
      "description_ar": "بفضل مخزون ضخم يتجاوز 120 ألف متر من السقالات و60 ألف متر مربع من الشدات المعتمدة، نضمن عدم تعطل الموقع وسرعة التوريد.",
      "icon_name": "local_shipping",
      "image_url": "images/industries/industrial-logistics.jpg",
      "display_order": 2,
      "is_active": 1
    },
    {
      "id": 3,
      "slug": "supervision",
      "name_en": "On-Site Technical Supervision",
      "name_ar": "الإشراف الفني الميداني واعتماد الصب",
      "summary_en": "Certified SCE temporary works field engineers conducting pre-pour audits, plumb checks, and early striking milestones.",
      "summary_ar": "مهندسون معتمدون من هيئة المهندسين السعوديين للتفتيش الميداني قبل كل صبة واعتماد الشدات ومتابعة مراحل الفك المبكر.",
      "description_en": "Safety is non-negotiable. Our resident site engineers inspect bolt torques, prop plumbing, anchor embedment, and wind tie-backs before signing digital pour permits.",
      "description_ar": "السلامة أولاً وأخيراً. يراجع مهندسونا عزم شد البراغي وشاقولية الدعامات ورسوخ المثبتات قبل التوقيع على تصاريح صب الخرسانة.",
      "icon_name": "supervisor_account",
      "image_url": "images/services/construction-management.jpg",
      "display_order": 3,
      "is_active": 1
    },
    {
      "id": 4,
      "slug": "sales",
      "name_en": "Equipment Sales & Custom Fabrication",
      "name_ar": "المبيعات وتصنيع القوالب الخاصة",
      "summary_en": "Direct acquisition of Saudi-manufactured steel moulds or certified ULMA systems with warranty, buyback options, and life tracking.",
      "summary_ar": "شراء مباشر للشدات المصنعة محلياً أو أنظمة أولما الأوروبية مع الضمان وخيارات إعادة الشراء وتتبع العمر الافتراضي.",
      "description_en": "Contractors seeking high-repetition assets can purchase bespoke steel shutters built in Riyadh or standard ULMA modular systems with technical warranties and refurbishment support.",
      "description_ar": "نوفر للمقاولين إمكانية التملك المباشر للقوالب والشدات المصنعة بمصنعنا بالرياض أو أنظمة أولما مع الصيانة والدعم الفني.",
      "icon_name": "shopping_cart",
      "image_url": "images/services/civil-structural.jpg",
      "display_order": 4,
      "is_active": 1
    },
    {
      "id": 5,
      "slug": "rental",
      "name_en": "Rental Fleet & Operations",
      "name_ar": "أسطول التأجير التشغيلي",
      "summary_en": "The Kingdom’s premier certified scaffolding and slab shoring rental fleet with flexible monthly terms aligned with project cash flows.",
      "summary_ar": "أكبر أسطول تأجير معتمد لسقالات وشدات الخرسانة بالمملكة بعقود شهرية مرنة تتناسب مع التدفقات المالية للمشروع.",
      "description_en": "Our massive rental pool lowers contractor capital expenditure while ensuring equipment meets strict SASO and European load benchmarks.",
      "description_ar": "يقلل أسطول التأجير من الأعباء الرأسمالية للمقاول مع ضمان خضوع كل قطعة لصيانة دورية صارمة وفحص جودة قبل كل تسليم.",
      "icon_name": "key",
      "image_url": "images/services/general-contracting.jpg",
      "display_order": 5,
      "is_active": 1
    }
  ],
  "assembly": [
    {
      "step_number": 1,
      "title_en": "Base Jack & Collar Alignment",
      "title_ar": "تثبيت وضبط القواعد اللولبية والأطواق",
      "description_en": "Heavy-duty base jacks anchored to engineered ground footings. Initial spindle adjustment guarantees 0.1° plumb line tolerance across irregular terrain.",
      "description_ar": "تثبيت القواعد اللولبية على أرضية مهيأة وضبط الارتفاع بمرونة ودقة لضمان استواء السقالة التام.",
      "spec_a_value": "45 kN Load Rating",
      "spec_a_label": "Base Spindle Capacity",
      "spec_b_value": "SASO ISO 3834-2",
      "spec_b_label": "Compliance Check",
      "image_url": "images/assembly/step1-base-jack.jpg"
    },
    {
      "step_number": 2,
      "title_en": "Vertical Standard Insertion",
      "title_ar": "تركيب القوائم الرأسية في الأطواق",
      "description_en": "Vertical standards fitted into base collars. Patented 8-hole rosette discs position at exact 500mm vertical increments.",
      "description_ar": "إسقاط القوائم الرأسية داخل أطواق القواعد مع توجيه أقراص الوردة الثمانية على ارتفاعات منتظمة بدقة 500 مم.",
      "spec_a_value": "3.2 mm S355 Steel",
      "spec_a_label": "Post Wall Thickness",
      "spec_b_value": "Max 1.5mm / 2m deviation",
      "spec_b_label": "Standard Plumb",
      "image_url": "images/assembly/step2-standards.jpg"
    },
    {
      "step_number": 3,
      "title_en": "Ledger Placement & Wedge Lock",
      "title_ar": "ربط العوارض الأفقية وإغلاق الإسفين",
      "description_en": "Horizontal ledgers connected at 90° intervals. Hammer blow engages captive wedge into rosette disc, securing rigid unyielding joint.",
      "description_ar": "ربط العوارض الأفقية على زوايا 90 درجة مع طرق الإسفين المدمج لإنشاء هيكل متين ومقاوم للالتواء.",
      "spec_a_value": "500 g Hammer Blow",
      "spec_a_label": "Wedge Engagement",
      "spec_b_value": "Over 14 kN·m resistance",
      "spec_b_label": "Node Joint Rigidity",
      "image_url": "images/assembly/step3-ledgers.jpg"
    },
    {
      "step_number": 4,
      "title_en": "Diagonal Spatial Bracing",
      "title_ar": "تثبيت المقصات القطرية للثبات الفراغي",
      "description_en": "Diagonal braces attached across alternate bays to establish triangulation and eliminate sway during high-elevation loads.",
      "description_ar": "تركيب المقصات القطرية لربط الباكيات بنظام المثلثات الهندسي لمنع أي اهتزاز أو انزياح تحت ضغط الرياح.",
      "spec_a_value": "45° Ideal Triangulation",
      "spec_a_label": "Brace Angle",
      "spec_b_value": "Class A Seismic Rating",
      "spec_b_label": "Sway Resistance",
      "image_url": "images/assembly/step4-bracing.jpg"
    },
    {
      "step_number": 5,
      "title_en": "Anti-Tilt Steel Planks",
      "title_ar": "تركيب ألواح المشايات الفولاذية المانعة للانزلاق",
      "description_en": "Perforated galvanized steel decks locked directly onto ledger profiles with integrated wind-lift security catches.",
      "description_ar": "إسقاط ألواح المشايات المجلفنة المثقبة وتثبيتها بمشابك أمان سفلية تمنع تطايرها بفعل الرياح الشديدة.",
      "spec_a_value": "Class 6 (6.0 kN/m²)",
      "spec_a_label": "Uniform Load Rating",
      "spec_b_value": "R11 Anti-Slip Surface",
      "spec_b_label": "Slip Resistance",
      "image_url": "images/assembly/step5-planks.jpg"
    },
    {
      "step_number": 6,
      "title_en": "Internal Access Trapdoors & Ladders",
      "title_ar": "تركيب السلالم الداخلية وبوابات العبور",
      "description_en": "Integrated aluminum inclined stairways or trapdoor decks installed to guarantee safe internal operative passage.",
      "description_ar": "تثبيت سلالم صعود ألومنيوم داخلية وبوابات أمان لضمان تنقل العمال دون تعريضهم لخطر الحواف المفتوحة.",
      "spec_a_value": "Gravity Spring Return",
      "spec_a_label": "Hatch Auto-Close",
      "spec_b_value": "150 kg Single User",
      "spec_b_label": "Ladder Capacity",
      "image_url": "images/assembly/step6-trapdoors.jpg"
    },
    {
      "step_number": 7,
      "title_en": "Advanced Guardrails & Toe Boards",
      "title_ar": "درابزينات الحماية المتقدمة وحواجز القدمين",
      "description_en": "Dual-tier guardrails and perimeter steel toe boards mounted before operatives step onto upper levels, achieving zero-fall risk.",
      "description_ar": "تركيب درابزينات الحماية المزدوجة وحواجز أطراف المشاية لحماية العمال والمعدات من السقوط بنسبة 100%.",
      "spec_a_value": "1.10 m Nominal Height",
      "spec_a_label": "Guardrail Height",
      "spec_b_value": "EN 12810 Full Compliance",
      "spec_b_label": "Certification",
      "image_url": "images/assembly/step7-guardrails.jpg"
    }
  ],
  "geometries": [
    {
      "id": "wall",
      "name_en": "Wall & Shear",
      "name_ar": "جدران وقص",
      "code": "ULMA ORMA + SM Walers",
      "title_en": "Monolithic Retaining & Shear Walls",
      "title_ar": "حوائط القص والجدران الاستنادية المصمتة",
      "desc_en": "Engineered for swift cycle repetitions. Integrates ULMA modular wall panels with locally fabricated high-load alignment struts to hold lateral pressure up to 80 kN/m².",
      "desc_ar": "مصممة لدورات صب سريعة ومتكررة. تدمج ألواح أورما المعيارية مع دعامات تقوية محلية تتحمل ضغط خرسانة حتى 80 كيلو نيوتن/م².",
      "image": "images/geometries/geometry-wall.jpg",
      "type_tag": "Vertical Formwork",
      "p1_label_en": "Pressure Capacity",
      "p1_label_ar": "تحمل ضغط الخرسانة",
      "p1_val": "80 kN/m²",
      "p2_label_en": "Striking Speed",
      "p2_label_ar": "سرعة الفك والتدوير",
      "p2_val": "0.25 hr/m²"
    },
    {
      "id": "column",
      "name_en": "Column",
      "name_ar": "أعمدة صقيلة",
      "code": "SM Rolled Shells + ULMA LGR",
      "title_en": "Circular & Rectangular High-Speed Columns",
      "title_ar": "الأعمدة الدائرية والمستطيلة فائقة النعومة",
      "desc_en": "Custom-rolled high-tensile steel half-cylinders and universal clamp assemblies for fair-faced columns up to 100 kN/m² pour speeds.",
      "desc_ar": "أنصاف قوالب فولاذية مدرفلة مخصصة لصب الأعمدة الصقيلة Class A بسرعة صب هيدروستاتيكي تصل إلى 100 كيلو نيوتن/م² بدون عيوب.",
      "image": "images/geometries/geometry-column.jpg",
      "type_tag": "Column & Pier",
      "p1_label_en": "Pour Pressure",
      "p1_label_ar": "ضغط الصب الأقصى",
      "p1_val": "100 kN/m²",
      "p2_label_en": "Diameter Range",
      "p2_label_ar": "أقطار متوفرة",
      "p2_val": "Ø300 – Ø2000mm"
    },
    {
      "id": "circular",
      "name_en": "Circular & Tanks",
      "name_ar": "خزانات وصوامع",
      "code": "ULMA BIRAMAX + SM Radius Walers",
      "title_en": "Curved Containment & Silo Structures",
      "title_ar": "المنشآت المنحنية وخزانات المياه والصوامع",
      "desc_en": "Continuously adjustable radius wall formwork engineered for wastewater treatment digesters and cylindrical water storage tanks.",
      "desc_ar": "شدات حوائط بنصف قطر قابل للتعديل المستمر مصممة لخزانات معالجة المياه وصوامع الحبوب والغاز الطبيعي المسال.",
      "image": "images/geometries/geometry-circular.jpg",
      "type_tag": "Curved Geometry",
      "p1_label_en": "Concrete Proof",
      "p1_label_ar": "مقاومة الضغط",
      "p1_val": "60 kN/m²",
      "p2_label_en": "Min Radius",
      "p2_label_ar": "أقل نصف قطر",
      "p2_val": "Radius ≥ 2.5m"
    },
    {
      "id": "slab",
      "name_en": "Slab & Deck",
      "name_ar": "أسقف وبلاطات",
      "code": "ULMA CC-4 Drop-Head + SM Props",
      "title_en": "Rapid Post-Tensioned & Flat Slabs",
      "title_ar": "الأسقف المستوية والبلاطات مسبقة الإجهاد",
      "desc_en": "Aluminum drop-head modular decking enabling 3-day striking cycles while leaving shoring props untouched, reducing inventory on-site by 40%.",
      "desc_ar": "نظام أسقف ألومنيوم برؤوس إسقاط سريعة يتيح فك الألواح بعد 3 أيام مع إبقاء الركائز داعمة، مما يخفض تكلفة المعدات بنسبة 40%.",
      "image": "images/geometries/geometry-slab.jpg",
      "type_tag": "Horizontal Decking",
      "p1_label_en": "Slab Thickness",
      "p1_label_ar": "سماكة البلاطة",
      "p1_val": "Up to 90cm",
      "p2_label_en": "Striking Cycle",
      "p2_label_ar": "دورة فك الشدة",
      "p2_val": "72 Hours"
    },
    {
      "id": "high-rise",
      "name_en": "High-Rise Core",
      "name_ar": "أبراج شاهقة",
      "code": "ULMA ATR Hydraulic Self-Climbing",
      "title_en": "Wind-Shielded High-Rise Cores",
      "title_ar": "قلوب الأبراج وأنظمة التسلق الهيدروليكي الآلي",
      "desc_en": "Crane-free self-climbing hydraulic system carrying multi-tiered placing booms, formwork panels, and weather shields up skyscraper towers.",
      "desc_ar": "منظومة تسلق ذاتية بدون رافعة برجية ترفع شدات الحوائط ومضخات الخرسانة وشاشات حماية الرياح لأطول ناطحات السحاب.",
      "image": "images/geometries/geometry-high-rise.jpg",
      "type_tag": "Climbing Systems",
      "p1_label_en": "Lifting Cylinder",
      "p1_label_ar": "قدرة المكبس",
      "p1_val": "100 kN Force",
      "p2_label_en": "Wind Safety",
      "p2_label_ar": "مقاومة الرياح",
      "p2_val": "72 km/h Safe"
    },
    {
      "id": "bridge",
      "name_en": "Bridge & Viaduct",
      "name_ar": "جسور وأنفاق",
      "code": "ULMA MK Carriage & Heavy Shoring",
      "title_en": "Cantilever & Launching Bridge Systems",
      "title_ar": "عربات صب الجسور وأبراج التدعيم الجبارة",
      "desc_en": "Specialized modular trusses for balanced cantilever bridges, composite decks, and high-clearance overpass flyovers.",
      "desc_ar": "جمالونات فولاذية متطورة للجسور المعلقة والأنفاق تتيح فتح مسارات مرورية عريضة أسفل منطقة العمل دون إغلاق الطرق.",
      "image": "images/geometries/geometry-bridge.jpg",
      "type_tag": "Heavy Civil Works",
      "p1_label_en": "Leg Capacity",
      "p1_label_ar": "تحمل القائم",
      "p1_val": "500 kN / Leg",
      "p2_label_en": "Clear Span",
      "p2_label_ar": "البحور المفتوحة",
      "p2_val": "Up to 24m"
    }
  ],
  "site": {
    "company_name_en": "Saudi Master Company",
    "company_name_ar": "شركة الماستر السعودي",
    "alliance_name_en": "Saudi Master × ULMA Construction Alliance",
    "alliance_name_ar": "تحالف الماستر السعودي مع أولما العالمية",
    "tagline_en": "Local Manufacturing. European Engineering. One Construction Partner.",
    "tagline_ar": "تصنيع سعودي محلي وهندسة أوروبية متقدمة من أولما",
    "phone": "+966 11 400 9800",
    "whatsapp": "+966500000000",
    "email": "engineering@saudimaster.com",
    "address_en": "Al-Malaz District, Industrial Corridor, PO Box 41293, Riyadh, KSA",
    "address_ar": "حي الملز، المنطقة الصناعية، ص.ب 41293، الرياض، المملكة العربية السعودية",
    "primary_accent": "#B58A52",
    "secondary_accent": "#B66E3C",
    "ulma_orange": "#E2882A",
    "vision_2030_partner": true,
    "license_no": "SM-ULMA-966-KSA",
    "social_links": {
      "linkedin": "https://linkedin.com/company/saudi-master-ulma",
      "twitter": "https://x.com/saudi_master",
      "youtube": "https://youtube.com/@saudimaster_ulma"
    },
    "default_seo": {
      "meta_title": "Saudi Master ULMA | Sovereign Formwork & Scaffolding Engineering KSA",
      "meta_description": "Saudi manufacturer & European ULMA engineering provider for formwork, scaffolding, heavy shoring, sales, rental, and supervision across Saudi Arabia."
    }
  }
};
